name = "main-store"
main = "worker.js"
compatibility_date = "2025-01-01"

[[d1_databases]]
binding = "DB"
database_name = "main-store"
database_id = "51899490-f529-4631-b5da-d93552ad920d"

[[kv_namespaces]]
binding = "FILES"
id = "499cc96ee4294a109d5036921fdcd6b5"

[vars]
MASTER_ADMIN_EMAIL = "you@example.com"
GOOGLE_CLIENT_ID = "YOUR_GOOGLE_OAUTH_CLIENT_ID.apps.googleusercontent.com"
ALLOWED_ORIGINS = "*"
